### ISSUE TITLE
[fixed in v6] v5.1.8 does not compile for watchOS through CocoaPods

### ISSUE THREAD

**Issue by herrjemand** [EFPrefix/EFQRCode#100]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFQRCode/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

### Issue Description

When using 5.1.8, I am getting "Could not build Objective-C module 'EFQRCode'"

My configuration:

WatchOS 6
Xcode 12

#### Reproduce

import EFQRCode

#### Other Comment

[Add anything else here]

**Comment by herrjemand** [comment]
Using 5.1.6 as specified in #85 did help

**Comment by ApolloZhu** [comment]
Starting v6 you should be able to integrate in the old way.
