### ISSUE TITLE
No such module 'EFQRCode'

### ISSUE THREAD

**Issue by jlubeck** [EFPrefix/EFQRCode#106]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFQRCode/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

### Issue Description
I just followed the Readme instruction and installed through SwiftPM, but when I try to use it with

`import EFQRCode` 

I get that error

`No such module 'EFQRCode'`

I'm trying to use it on a WatchOS only app.

**Comment by ApolloZhu** [comment]
Make sure you are adding `EFQRCode` to the correct target (i.e. the Extension):
![image](https://user-images.githubusercontent.com/10842684/100172609-b1ecf280-2e96-11eb-86f7-b4dadb16e84e.png)

... or manually add `EFQRCode` as a Framework for your extension target:
![image](https://user-images.githubusercontent.com/10842684/100172517-84a04480-2e96-11eb-93c0-7a0a1706d18b.png)

**Comment by jlubeck** [comment]
Thank you. That was it
