### ISSUE TITLE
In Xcode 12.2 using swift package with library 6.0.0, compiler issues warning

### ISSUE THREAD

**Issue by Dlemex** [EFPrefix/EFQRCode#110]
### Issue Description

After adding EFQRCode using Xcode 12.2 swift packages, the package manager reports a warning for 2 files.  The two plist files are not handled.
 

Showing All Messages
found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    .../EFQRCode/Source/info-tvos.plist
    .../EFQRCode/Source/info.plist

#### Description

The warning is produced during the Resolve Package Graph step.

#### Reproduce

In any project, running inside Xcode 12.2, File->Swift Packages->Add Package Dependency 
  enter EFPrefix/EFQRCode with a version of 6.0.0
Compile the project for the warning.  It will occur before the compilation of the project starts.

**Comment by ApolloZhu** [comment]
Fixed in main.

Since this is a warning and v6 is under pre-release, you might need to wait until #109 to be merged and released to see this fix in a tagged/versioned release.

**Comment by Dlemex** [comment]
Thanks for the quick reply.  I will wait for your next merge.
