### ISSUE TITLE
'EFQRCode-Swift.h' file not found 新建了一个OC新库 依赖于EFQRCode

### ISSUE THREAD

**Issue by ccworld1000** [EFPrefix/EFQRCode#148]
### 检查清单

- [x ] 我已阅读 [README.md](https://github.com/EFPrefix/EFQRCode/blob/main/README_CN.md)，但没找到我需要的信息。
- [x ] 我已查看 [已知的问题](https://github.com/EFPrefix/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue)，但没有相似的提问/请求。

### 问题描述
'EFQRCode-Swift.h' file not found 新建了一个OC新库 依赖于EFQRCode
<img width="1117" alt="Screen Shot 2022-08-08 at 17 32 48" src="https://user-images.githubusercontent.com/22360168/183387532-5f06e827-1b9b-4c1c-a3c5-5091f3f7b643.png">

#### 展开讲讲

<img width="1117" alt="Screen Shot 2022-08-08 at 17 32 48" src="https://user-images.githubusercontent.com/22360168/183387532-5f06e827-1b9b-4c1c-a3c5-5091f3f7b643.png">

#### 重现步骤

新建一个测试库依赖EFQRCode -> s.dependency 'EFQRCode', '~> 6.2.1' (采用Pod导入)
环境 Xcode14、Swift5.7
导入头文件
#import <EFQRCode-Swift.h>

#### 其他信息

使用Pod导入

**Comment by ApolloZhu** [comment]
我对 Objective-C 不是特别熟悉，但根据我的理解，应该可以用 `@import EFQRCode` 或者 `#import <EFQRCode/EFQRCode.h>` 来导入？
