### ISSUE TITLE
Compressed image will not be set as watermark

### ISSUE THREAD

**Issue by vin-zhou** [EFPrefix/EFQRCode#38]
The judgement of isGIF in GeneratorController.swift Line 1079  will defend using the compressed image returned from selectedAlbumPhotosIncludingGifWithPHAssets, which seems a bug.

**Comment by EyreFree** [comment]
Only type 'kUTTypeGIF' image will make 'isGIF' true, in `GeneratorController.swift` Line 1079.

**Comment by ApolloZhu** [comment]
Might be relevant https://developer.apple.com/documentation/photokit/phimagerequestoptions/1616934-networkaccessallowed
