### ISSUE TITLE
Will the latest release version supported Objective-c?

### ISSUE THREAD

**Issue by KinGwaL** [EFPrefix/EFQRCode#45]
Latest release version seems not support Objective-c as i cannot see any external function at EFQRCode-Swift.h file ..

**Comment by EyreFree** [comment]
1. There is no plan to support `Objective-C` at present. If you are interested, you can submit your pull requests to this project.
2. Or, maybe you can use [YSQRCode](https://github.com/z624821876/YSQRCode) instead.
