### ISSUE TITLE
iOS 12 impossible to generate QR code.

### ISSUE THREAD

**Issue by OlegGordiichuk** [EFPrefix/EFQRCode#46]
I am using this lib to generate qr codes. But for iOS 12 it always fails to generate qr code.

After some investigation i found out that in iOS 12 filter **CIFilter(name: "CIQRCodeGenerator")**  always return nil.

**Comment by EyreFree** [comment]
I will check this today, thanks.

**Comment by EyreFree** [comment]
It works fine on my iPhone 6s with iOS 12.0(16A5288q), can you provide more details?

```
Device:
OS Version(In detail):
EFQRCode Version:
```

Or some other information may be useful, thanks!

**Comment by OlegGordiichuk** [comment]
After some research and testing I can admit that this issue only occurs on the iOS 12 emulator.

@EyreFree so I think this issue could be closed.

**Comment by EyreFree** [comment]
@OlegGordiichuk 

OK, I will check this problem on the iOS 12 simulator later, thanks for your work.

**Comment by xhl916235259** [comment]
I have also encountered this crash problem, which has been solved just now. The specific reason is the problem caused by your application or the third-party module reference fishhook, which only needs to be removed. For example, Bugtagss detection tool I use causes flash back
