### ISSUE TITLE
Keep space around logo, generate QR pixel around the Logo

### ISSUE THREAD

**Issue by RahulTBI** [EFPrefix/EFQRCode#60]
I want QR code with company logo, but i want it centre of the QR code and some space around the logo so it looks clean.

Thanks
RahulTBI

**Comment by EyreFree** [comment]
@RahulTBI 

You should modify icon image, [SwiftyImage](https://github.com/devxoul/SwiftyImage) may be what you need.

**Comment by RahulTBI** [comment]
@EyreFree 

Thanks for instant reply
