### ISSUE TITLE
Consider adding 'pasting icons' feature

### ISSUE THREAD

**Issue by Loovemaker** [EFPrefix/EFQRCode#61]

**Comment by Loovemaker** [comment]
I want to just Ctrl+C Ctrl+V my favored app icons into EFQRCode (e.g. for my QRCode of Github accounts) just like: 
[关于代表您 Mac 上的文件的图标](https://support.apple.com/HT201737)

**Comment by ApolloZhu** [comment]
This is a native macOS behavior and is confirmed to be working. Should you still have trouble replacing the icon, please contact Apple Support.
