### ISSUE TITLE
Support generating barcode type CICode128BarcodeGenerator

### ISSUE THREAD

**Issue by SebastianZalewski** [EFPrefix/EFQRCode#64]
Is it possible to generate CICode128BarcodeGenerator on watchOS? CIFilter is not available and I don't want to create barcode on the iPhone and send it later to watch. Is it possible with EFQRCode?

**Comment by ApolloZhu** [comment]
EFQRCode does not support anything other than QR code on any platform currently #63

**Comment by ApolloZhu** [comment]
Wait for this year’s WWDC to see if watchOS is going to be more independent ;)

**Comment by SebastianZalewski** [comment]
> Wait for this year’s WWDC to see if watchOS is going to be more independent ;)

Hmm I believe they decided to make watchOS more independent but there is still no way to generate 2d barcode on apple watch itself, right?

**Comment by ApolloZhu** [comment]
You are right...

So here’s the thing: support for QRCode generation is achieved through swift_qrcodejs. I would recommend finding another/or creating your own library that generates barcode with pure Swift or in another language.

EFQRCode is more focused on the styling aspect of QRCode generation and majority of the code are tailored to accomplish that task, therefore I don’t see it adding support for another format in the near future (probably why #63 is closed)
