### ISSUE TITLE
Carthage installation problem

### ISSUE THREAD

**Issue by abdulhaq-e** [EFPrefix/EFQRCode#65]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ X] I have read the [README.md](https://github.com/EFPrefix/EFQRCode/blob/master/README.md), but there is no information I need.
- [ X] I have searched in [existing issues](https://github.com/EFPrefix/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

Since version 5, the library cannot be installed using Carthage. Searching for the returned error on the internet, I got many results back but all solutions don't work. This is the returned error:

`A shell task (/usr/bin/env git checkout --quiet 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9 (launched in /Users/project/Carthage/Checkouts/EFQRCode/Examples/3rd/SnapKit)) failed with exit code 128:
fatal: reference is not a tree: 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9`

#### Reproduce

Add this to the `Cartfile` and run `carthage update`:

`github "EFPrefix/EFQRCode"`

Pinning a version also doesn't work. The only thing that works for me is using version 4 from your personal github account:

`github "EyreFree/EFQRCode" ~> 4.3.0`

#### Other Comment

Tested on multiple devices, same result.

Thanks for this great library!

**Comment by EyreFree** [comment]
@abdulhaq-e 

There is something wrong with EFQRCode for watchOS in Carthage, you can use `platform` parameter to avoid this problem:

```
carthage update --platform iOS,macOS,tvOS
```

We'll fix it later.

**Comment by SebastianZalewski** [comment]
Any update on that?

**Comment by LeoAiolia** [comment]
same The problem
A shell task (/usr/bin/env git checkout --quiet 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9 (launched in /Users/dev-yxr/Desktop/CarthageTest/Carthage/Checkouts/EFQRCode/Examples/3rd/SnapKit)) failed with exit code 128:
fatal: reference is not a tree: 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9

**Comment by desmondYing** [comment]
I got the same problem!

github "EFPrefix/EFQRCode"

A shell task (/usr/bin/env git checkout --quiet 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9 (launched in /Users/des/Desktop/des/Carthage/Checkouts/EFQRCode/Examples/3rd/SnapKit)) failed with exit code 128:
fatal: reference is not a tree: 122809d12f0a3ed8323d2e6b3ddc7ec107a6afc9

**Comment by EyreFree** [comment]
@abdulhaq-e 
@SebastianZalewski 
@LeoAiolia 
@desmondYing 

Fixed in [5.0.1](https://github.com/EFPrefix/EFQRCode/releases/tag/5.0.1).
