### ISSUE TITLE
Wrong year in changelog.

### ISSUE THREAD

**Issue by Zandor300** [EFPrefix/EFQRCode#71]
The CHANGELOG.md file says year 2018 for the 5.0.1 and 5.1.0 releases. Should be 2019.

**Comment by EyreFree** [comment]
Thanks for pointing out the mistake, it has been corrected in [65d44fa](https://github.com/EFPrefix/EFQRCode/commit/65d44fa221dfece074ebbf9c8d4d580b019605e4).
