### ISSUE TITLE
Fix Failing CI

### ISSUE THREAD

**Issue by ApolloZhu** [EFPrefix/EFQRCode#79]
As we can see on https://travis-ci.org/EFPrefix/EFQRCode, all the tests are failing due to missing simulators. From [this StackOverflow answer](https://stackoverflow.com/a/36168576), we can install the necessary simulators within the execution of each matrix configuration.

## Note

There's a patch for iOS 9.3 simulator, which should now be executed for that configuration only, or completely removed if that's no longer necessary.

**Comment by EyreFree** [comment]
![](https://user-images.githubusercontent.com/10757132/69417826-6cae5600-0d54-11ea-9d48-05b7c8ddc4f3.png)

**Comment by ApolloZhu** [comment]
Should be fixed
