### ISSUE TITLE
error:No such module 'EFFoundation'

### ISSUE THREAD

**Issue by sunmomomo** [EFPrefix/EFQRCode#80]
没找到这个framework

**Comment by EyreFree** [comment]
@sunmomomo 

可否提供一些详细信息，

请问你是通过哪种依赖管理方式使用本库，CocoaPods / SPM / Carthage？

你的目标平台是 iOS, macOS, watchOS 还是 tvOS？

**Comment by sunmomomo** [comment]
我直接下载的，想先看看效果，iOS平台

**Comment by ApolloZhu** [comment]
![image](https://user-images.githubusercontent.com/10842684/67370983-7d3e9700-f530-11e9-9c6f-abd02e9119c1.png)

**Comment by sunmomomo** [comment]
OK，我试一试，刚刚没看到
