### ISSUE TITLE
Documentation for watchOS Podspec missing

### ISSUE THREAD

**Issue by ristkof** [EFPrefix/EFQRCode#83]
### Issue Description

Using the podspec on WatchOS is undocumented

#### Description

Before [this commit](https://github.com/EFPrefix/EFQRCode/commit/54650f472277a317df2d714b9f1c8ebe70b4cb10#diff-b8eca54941cf696b2104a3e9a2ecc3d2) I was using the regular podcast spec on watchOS, and it worked.

Now I *think* I need to use `pod 'EFQRCode/watchOS'` but after `pod install`ing that, there is no EFQRCode module installed.

More specifically, cocoapods seems to download and add EFQRCode as a module, but the project does not contain any source files. It looks like on watchOS it has been replaced by a dummy EFQRCode module.

Am I doing it wrong? Some documentation on the specifics of using this subspec on watchOS would be appreciated!

**Comment by EyreFree** [comment]
@ristkof 

Fixed in [5.1.6](https://github.com/EFPrefix/EFQRCode/releases/tag/5.1.6), you can have a try.

**Comment by ristkof** [comment]
Works! Thanks.
