### ISSUE TITLE
Watch OS Compatibility

### ISSUE THREAD

**Issue by hugod-g** [EFPrefix/EFQRCode#85]
Hello ! 

In your READ.ME, you tell that your lib is compatible with Watch OS, but pod say that its not.

Is it still compatible ?

**Comment by EyreFree** [comment]
@hugod-g 

It's still compatible, you can use `pod 'EFQRCode/watchOS'`.

The default subspec `Core` does not support `watchOS`, so it is not included in pod badge, we will fix it soon.

**Comment by hugod-g** [comment]
Pod installation is done, but which is the import then ? Because "import EFQRCode" is not recognize

**Comment by EyreFree** [comment]
@hugod-g 

Try [5.1.6](https://github.com/EFPrefix/EFQRCode/releases/tag/5.1.6).

**Comment by hugod-g** [comment]
Thank you, it works fine now.

The only thing is that i need to download 5.1.6 version and to link it with a path on the podspec, pod install is not working with "pod 'EFQRCode/watchOS',  '~> 5.1.6'".

**Comment by EyreFree** [comment]
@hugod-g 

It works fine on my computer, have you tried `pod repo update`?

![](https://user-images.githubusercontent.com/10757132/69621720-9b8d3a80-107a-11ea-9fc5-504900214d77.png)

**Comment by hugod-g** [comment]
Good for me.

Thank you, best regards
