### ISSUE TITLE
Carthage update failure

### ISSUE THREAD

**Issue by rafabertholdo** [EFPrefix/EFQRCode#86]
Hi, I'm trying to install the framework via Carthage but i'm receiving the following error:

error: compiling for watchOS 2.0, but module 'swift_qrcodejs' has a minimum deployment target of watchOS 6.1:

my cartfile: 
github "EFPrefix/EFQRCode" ~> 5.1.6

Command I'm using
Carthage update EFQRCode --platform watchOS

**Comment by ApolloZhu** [comment]
Update: I'm unfamiliar with Carthage, but it appears that adding swift_qrcodejs as the only dependency compiles for watchOS 2.0. 

You might want to temporarily consider alternatives (such as SPM/CocoaPods/submodule) while I am investigating on how to fix this.

**Comment by ApolloZhu** [comment]
Looks like a Carthage problem: https://github.com/Carthage/Carthage/issues/2735

**Comment by ApolloZhu** [comment]
Closing since Carthage is building normally now
