### ISSUE TITLE
能否出一个OC版本

### ISSUE THREAD

**Issue by coderchou** [EFPrefix/EFQRCode#92]

**Comment by ApolloZhu** [comment]
目前是可以在 Objective-C 工程中使用 EFQRCode 的，但可能会缺少部分 API。

下一个版本 #109 会对 API 进行调整，确保 Swift 和 OC 都能有良好的使用体验。您可以提前试用 objc 分支的代码，也欢迎您反馈对新 API 的意见和建议。
