### ISSUE TITLE
关于style问题

### ISSUE THREAD

**Issue by crazypoo** [EFPrefix/EFQRCode#93]
请问有没有可以生成类似微信小程序码的风格?

**Comment by EyreFree** [comment]
不可以。

小程序码的编码协议是毕源 & 私有的，目前市面上没有找到可以本地生成小程序码的非微信官方工具（有的话可以 @ 我看看）。

参考：[https://zhuanlan.zhihu.com/p/85164898](https://zhuanlan.zhihu.com/p/85164898)

**Comment by crazypoo** [comment]
不是,我的意思是可不可以生成二维码,是类似小程序二维码的风格
